name: lint-and-unit-tests

on:
  pull_request:
  push:
    branches:
      - github
      - main
      - master
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

jobs:
  build-and-test-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.6"
          - "3.8"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Clone StackStorm/st2 repo
        run: |
          make .clone_st2_repo

      - name: Download and install depedencies
        run: |
          sudo apt-get update
          sudo apt-get -y install libldap2-dev libsasl2-dev
          sudo apt-get -y install python3-virtualenv
          make requirements

      - name: Run lint and tests (Python ${{ matrix.version }})
        run: |
          make .lint
          make .unit-tests
